### ISSUE TITLE
Error: Unexpected Response: utils.isBuffer is not a function at /projectfolder/node_modules/jscrambler/dist/client.js:211:11

### ISSUE THREAD

**Issue by ACECEO** [jscrambler/jscrambler#49]
After updating Mac OS to 10.14.6 from 10.14.5 I get the following issue when performing cordova build ios

Running command: 
/projectfolder/hooks/after_prepare/020_jscrambler.js 
/projectfolder
Signature data: POST;api4.jscrambler.com;/application;access_key=redactedforsecurity

Error: Unexpected Response: utils.isBuffer is not a function
    at /projectfolder/node_modules/jscrambler/dist/client.js:211:11

Everything else is good. Project builds successfully except for jscrambler code protection.

**Comment by ACECEO** [comment]
I pulled an older project and found this works, couldn't find any differences at the obvious level so I am guessing  something in my project, which I could not identify, got corrupted. I used the old project, brought it current, and everything works.
